### ISSUE TITLE
Release Chores

### ISSUE THREAD

**Issue by LinusBorg** [LinusBorg/portal-vue#10]
## Todos
- [x] Prepare Package.json for publishing (github links, description, version, `main:`, cleanup dependencies  ...)
- [x] Update Vue-loader to 11.0.0
- [x] Improve Examples code & design

**Comment by LinusBorg** [comment]
done
